// Dependency-free prerendering. Shared public headers and footers come from app.js.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'..');
const scope={Intl,structuredClone,location:{hash:'',pathname:'/'},localStorage:{getItem(){return null}},window:{addEventListener(){}},document:{addEventListener(){}}};
vm.createContext(scope);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/render\(\);\s*$/,''),scope);
const run=code=>vm.runInContext(code,scope);
const domain='https://travauxcorse.com';
const routes=[['home','', 'TravauxCorse | Artisans et travaux en Corse','Déposez votre projet de travaux en Corse. TravauxCorse facilite la mise en relation avec les artisans et fournisseurs en Haute-Corse et Corse-du-Sud.'],['energy','travaux-energetiques','Rénovation énergétique en Corse | TravauxCorse','Isolation, climatisation, chauffage, ventilation et photovoltaïque : préparez votre rénovation énergétique en Corse avec TravauxCorse.'],['suppliers','partenaires','Fournisseurs et matériaux en Corse | TravauxCorse','Organisez les fournitures de votre chantier en Corse : matériaux, électricité, plomberie, chauffage et menuiserie.'],['request','deposer-une-demande','Demande de devis travaux en Corse | TravauxCorse','Décrivez votre chantier en Corse, sélectionnez plusieurs métiers et joignez vos photos ou plans. Une demande gratuite et sans engagement.'],['partner','devenir-partenaire','Devenir artisan ou fournisseur partenaire | TravauxCorse','Artisans, entreprises du bâtiment et fournisseurs en Corse : proposez votre candidature au réseau TravauxCorse.']];
function head(title,description,url){return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta name="theme-color" content="#24211e"><link rel="canonical" href="${url}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:type" content="website"><meta property="og:locale" content="fr_FR"><meta property="og:site_name" content="TravauxCorse"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:image" content="${domain}/social-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/styles.css">`;}
for(const [page,dir,title,description] of routes){run(`state.page=${JSON.stringify(page)}`);const html=run('`<div class="site-shell">${renderHeader()}<main id="main-content">${renderPage()}</main>${renderFooter()}</div>`');const output=`<!doctype html><html lang="fr"><head>${head(title,description,domain+'/'+(dir?dir+'/':''))}${page==='home'?'<script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'TravauxCorse',legalName:'UNITI INSEME LIMITED',url:domain,email:'contact.travauxcorse@gmail.com',telephone:'+33771815090',areaServed:['Haute-Corse','Corse-du-Sud'],description:'Plateforme de mise en relation entre particuliers, professionnels du bâtiment et fournisseurs en Corse.'})+'</script>':''}</head><body><a class="skip-link" href="#main-content">Aller au contenu</a><noscript><p class="notice">Activez JavaScript pour utiliser les formulaires. Vous pouvez aussi nous joindre au <a href="tel:+33771815090">07 71 81 50 90</a> ou à <a href="mailto:contact.travauxcorse@gmail.com">contact.travauxcorse@gmail.com</a>.</p></noscript><div id="app">${html}</div><script defer src="/navigation.js"></script><script defer src="/app.js"></script></body></html>`;fs.mkdirSync(path.join(root,dir),{recursive:true});fs.writeFileSync(path.join(root,dir,'index.html'),output);}
run('state.page="home"');const header=run('renderHeader()').replace(/ aria-current="page"/g,'').replace(/ data-page="[^"]*"/g,''),footer=run('renderFooter()');
fs.writeFileSync(path.join(root,'lib/content-layout.json'),JSON.stringify({header,footer},null,2));
function htmlFiles(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?htmlFiles(path.join(dir,d.name)):d.name==='index.html'?[path.join(dir,d.name)]:[]);}
for(const file of htmlFiles(root)){if(routes.some(([,dir])=>file===path.join(root,dir,'index.html')))continue;let html=fs.readFileSync(file,'utf8');const relative=path.relative(root,path.dirname(file)).split(path.sep).join('/');const active=relative.startsWith('conseils')?'/conseils/':relative.startsWith('realisations')?'/realisations/':null;html=html.replace(/<header\b[^>]*>[\s\S]*?<\/header>/,active?header.replace(`href="${active}"`,`href="${active}" aria-current="page"`):header).replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/,footer).replace(/<link[^>]+(?:fonts\.googleapis|fonts\.gstatic)[^>]*>/g,'');if(!html.includes('id="main-content"'))html=html.replace('<main','<main id="main-content"');if(!html.includes('class="skip-link"'))html=html.replace(/(<body[^>]*>)/,'$1<a class="skip-link" href="#main-content">Aller au contenu</a>');const title=html.match(/<title>(.*?)<\/title>/)?.[1]||'TravauxCorse';const desc=html.match(/name="description" content="([^"]*)"/)?.[1]||'Découvrez les services TravauxCorse et les informations utiles pour votre projet.';html=html.replace(/<link[^>]+rel="canonical"[^>]*>/g,'').replace(/<link[^>]+rel="icon"[^>]*>/g,'').replace(/<meta[^>]+(?:property="og:|name="twitter:)[^>]*>/g,'');html=html.replace('</head>',`<link rel="canonical" href="${domain}/${relative}/"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:type" content="${relative.startsWith('conseils/')?'article':'website'}"><meta property="og:url" content="${domain}/${relative}/"><meta property="og:image" content="${domain}/social-card.png"><meta name="twitter:card" content="summary_large_image"></head>`);fs.writeFileSync(file,html);}
const urls=htmlFiles(root).map(f=>path.relative(root,path.dirname(f)).split(path.sep).join('/')).filter(d=>!['admin','tests'].some(x=>d===x||d.startsWith(x+'/')));fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(d=>`<url><loc>${domain}/${d?d+'/':''}</loc></url>`).join('\n')+'\n</urlset>\n');
console.log('Prerendered '+routes.length+' public routes; shared layout and sitemap updated.');
